// src/data.js
export const mockPatient = {
  id: 1,
  first_name: "James",
  last_name: " Wamaitha",
  email: "JamesWamiatha@gmail.com",
  password: "telecure123",
  phone: "0712345678",
  nationality: "Kenyan",
  emergency_contact_name: "Patrick Mulwa",
  emergency_phone: "0712345678",
  dob: "1983-01-01",
  gender: "Female",
  address: "Nairobi, Kenya",
  blood_type: "O+",
  allergies: "None",
  diseases: "None",
  card: {
    name: "James Wamaitha",
    number: "XXXX XXXX XXXX 3456",
    expiry: "12/25",
    cvv: "256",
  },
};

// src/doctorData.js

export const doctors = [
  {
    id: 1,
    first_name: "Joe",
    last_name: "Doe",
    avatar: "https://ui-avatars.com/api/?name=Joe+Doe",
    email: "joedoe@gmail.com",
    phone: "0712345678",
    nationality: "Kenyan",
    dob: "1983-01-01",
    gender: "Male",
    address: "Nairobi, Kenya",
    emergency_contact_name: "Patrick Doe",
    emergency_phone: "0712345678",
    specialization: "Cardiology, Neurology",
    university: "University of Nairobi",
    experience: 10,
    license: "123456789",
    certifications: "Board Certified in Cardiology",
    hospital: "Nairobi Hospital",
    hospital_address: "Nairobi, Kenya",
    hours: "Mon-Fri: 8 AM - 5 PM",
    fee: "KES 3000",
    available_online: "Yes",
    bio: "Dr. Joe Doe is a highly experienced cardiologist and neurologist.",
    card: {
      name: "Joe Doe",
      number: "XXXX XXXX XXXX 3456",
      expiry: "12/25",
      cvv: "256",
    },
  },
  {
    id: 2,
    first_name: "Grace",
    last_name: "Mutiso",
    avatar: "https://ui-avatars.com/api/?name=Grace+Mutiso",
    email: "grace.mutiso@gmail.com",
    phone: "0700123456",
    nationality: "Kenyan",
    dob: "1985-06-15",
    gender: "Female",
    address: "Mombasa, Kenya",
    emergency_contact_name: "Ann Mutiso",
    emergency_phone: "0711223344",
    specialization: "Pediatrics",
    university: "Kenyatta University",
    experience: 8,
    license: "987654321",
    certifications: "Board Certified in Pediatrics",
    hospital: "Coast General Hospital",
    hospital_address: "Mombasa, Kenya",
    hours: "Mon-Fri: 9 AM - 4 PM",
    fee: "KES 2500",
    available_online: "Yes",
    bio: "Dr. Grace Mutiso has been serving children for over 8 years.",
    card: {
      name: "Grace Mutiso",
      number: "XXXX XXXX XXXX 1234",
      expiry: "11/24",
      cvv: "123",
    },
  },
  {
    id: 3,
    first_name: "David",
    last_name: "Otieno",
    avatar: "https://ui-avatars.com/api/?name=David+Otieno",
    email: "david.otieno@gmail.com",
    phone: "0722334455",
    nationality: "Kenyan",
    dob: "1978-04-10",
    gender: "Male",
    address: "Kisumu, Kenya",
    emergency_contact_name: "Peter Otieno",
    emergency_phone: "0799887766",
    specialization: "Orthopedics",
    university: "Maseno University",
    experience: 15,
    license: "654987321",
    certifications: "Orthopedic Specialist",
    hospital: "Kisumu County Hospital",
    hospital_address: "Kisumu, Kenya",
    hours: "Tue-Sat: 8 AM - 3 PM",
    fee: "KES 3500",
    available_online: "No",
    bio: "Dr. David Otieno specializes in bone and joint treatment.",
    card: {
      name: "David Otieno",
      number: "XXXX XXXX XXXX 4321",
      expiry: "10/26",
      cvv: "987",
    },
  },
  {
    id: 4,
    first_name: "Linda",
    last_name: "Njeri",
    avatar: "https://ui-avatars.com/api/?name=Linda+Njeri",
    email: "linda.njeri@gmail.com",
    phone: "0799112233",
    nationality: "Kenyan",
    dob: "1990-09-25",
    gender: "Female",
    address: "Thika, Kenya",
    emergency_contact_name: "Wambui Njeri",
    emergency_phone: "0711002233",
    specialization: "Dermatology",
    university: "University of Nairobi",
    experience: 7,
    license: "456789123",
    certifications: "Certified Dermatologist",
    hospital: "Thika Level 5 Hospital",
    hospital_address: "Thika, Kenya",
    hours: "Mon-Fri: 10 AM - 6 PM",
    fee: "KES 2000",
    available_online: "Yes",
    bio: "Dr. Linda Njeri is passionate about healthy skin care.",
    card: {
      name: "Linda Njeri",
      number: "XXXX XXXX XXXX 6789",
      expiry: "09/25",
      cvv: "456",
    },
  },
  {
    id: 5,
    first_name: "Peter",
    last_name: "Kimani",
    avatar: "https://ui-avatars.com/api/?name=Peter+Kimani",
    email: "peter.kimani@gmail.com",
    phone: "0733445566",
    nationality: "Kenyan",
    dob: "1980-12-05",
    gender: "Male",
    address: "Nakuru, Kenya",
    emergency_contact_name: "Mercy Kimani",
    emergency_phone: "0700112233",
    specialization: "Psychiatry",
    university: "Egerton University",
    experience: 12,
    license: "112233445",
    certifications: "Mental Health Specialist",
    hospital: "Nakuru PGH",
    hospital_address: "Nakuru, Kenya",
    hours: "Wed-Sun: 10 AM - 4 PM",
    fee: "KES 3000",
    available_online: "Yes",
    bio: "Dr. Peter Kimani focuses on improving mental health awareness.",
    card: {
      name: "Peter Kimani",
      number: "XXXX XXXX XXXX 5678",
      expiry: "08/24",
      cvv: "321",
    },
  },
  {
    id: 6,
    first_name: "Susan",
    last_name: "Mwangi",
    avatar: "https://ui-avatars.com/api/?name=Susan+Mwangi",
    email: "susan.mwangi@gmail.com",
    phone: "0700556677",
    nationality: "Kenyan",
    dob: "1987-03-20",
    gender: "Female",
    address: "Eldoret, Kenya",
    emergency_contact_name: "James Mwangi",
    emergency_phone: "0744332211",
    specialization: "Gynecology",
    university: "Moi University",
    experience: 9,
    license: "789654123",
    certifications: "Certified OB/GYN",
    hospital: "Eldoret Hospital",
    hospital_address: "Eldoret, Kenya",
    hours: "Mon-Fri: 8 AM - 2 PM",
    fee: "KES 2800",
    available_online: "No",
    bio: "Dr. Susan Mwangi supports women's health at all stages.",
    card: {
      name: "Susan Mwangi",
      number: "XXXX XXXX XXXX 9012",
      expiry: "05/26",
      cvv: "654",
    },
  },
  {
    id: 7,
    first_name: "Brian",
    last_name: "Ouma",
    avatar: "https://ui-avatars.com/api/?name=Brian+Ouma",
    email: "brian.ouma@gmail.com",
    phone: "0744112233",
    nationality: "Kenyan",
    dob: "1991-11-11",
    gender: "Male",
    address: "Machakos, Kenya",
    emergency_contact_name: "Emily Akinyi",
    emergency_phone: "0722009988",
    specialization: "General Practice",
    university: "Jomo Kenyatta University",
    experience: 5,
    license: "998877665",
    certifications: "General Medical License",
    hospital: "Machakos Level 5 Hospital",
    hospital_address: "Machakos, Kenya",
    hours: "Daily: 9 AM - 3 PM",
    fee: "KES 1800",
    available_online: "Yes",
    bio: "Dr. Brian Ouma offers quality and affordable medical care.",
    card: {
      name: "Brian Ouma",
      number: "XXXX XXXX XXXX 5555",
      expiry: "04/25",
      cvv: "111",
    },
  },
  {
    id: 8,
    first_name: "Faith",
    last_name: "Chebet",
    avatar: "https://ui-avatars.com/api/?name=Faith+Chebet",
    email: "faith.chebet@gmail.com",
    phone: "0755332211",
    nationality: "Kenyan",
    dob: "1994-07-07",
    gender: "Female",
    address: "Kericho, Kenya",
    emergency_contact_name: "John Chebet",
    emergency_phone: "0700778899",
    specialization: "Oncology",
    university: "Kisii University",
    experience: 6,
    license: "334455667",
    certifications: "Cancer Specialist",
    hospital: "Kericho Hospital",
    hospital_address: "Kericho, Kenya",
    hours: "Mon-Fri: 8 AM - 1 PM",
    fee: "KES 4000",
    available_online: "Yes",
    bio: "Dr. Faith Chebet is dedicated to supporting cancer patients.",
    card: {
      name: "Faith Chebet",
      number: "XXXX XXXX XXXX 8888",
      expiry: "07/26",
      cvv: "222",
    },
  },
  {
    id: 9,
    first_name: "Kelvin",
    last_name: "Mwenda",
    avatar: "https://ui-avatars.com/api/?name=Kelvin+Mwenda",
    email: "kelvin.mwenda@gmail.com",
    phone: "0723445566",
    nationality: "Kenyan",
    dob: "1982-08-18",
    gender: "Male",
    address: "Meru, Kenya",
    emergency_contact_name: "Lucy Mwenda",
    emergency_phone: "0700445566",
    specialization: "ENT",
    university: "Chuka University",
    experience: 11,
    license: "556677889",
    certifications: "ENT Specialist",
    hospital: "Meru Level 5",
    hospital_address: "Meru, Kenya",
    hours: "Mon-Sat: 9 AM - 3 PM",
    fee: "KES 2600",
    available_online: "No",
    bio: "Dr. Kelvin Mwenda treats ear, nose, and throat conditions.",
    card: {
      name: "Kelvin Mwenda",
      number: "XXXX XXXX XXXX 2222",
      expiry: "06/24",
      cvv: "333",
    },
  },
  {
    id: 10,
    first_name: "Esther",
    last_name: "Wanjiku",
    avatar: "https://ui-avatars.com/api/?name=Esther+Wanjiku",
    email: "esther.wanjiku@gmail.com",
    phone: "0766778899",
    nationality: "Kenyan",
    dob: "1986-02-28",
    gender: "Female",
    address: "Nyeri, Kenya",
    emergency_contact_name: "Mary Wanjiku",
    emergency_phone: "0722003322",
    specialization: "Endocrinology",
    university: "Dedan Kimathi University",
    experience: 13,
    license: "112211334",
    certifications: "Hormonal Specialist",
    hospital: "Nyeri County Hospital",
    hospital_address: "Nyeri, Kenya",
    hours: "Tue-Fri: 8 AM - 2 PM",
    fee: "KES 3500",
    available_online: "Yes",
    bio: "Dr. Esther Wanjiku helps manage hormonal disorders.",
    card: {
      name: "Esther Wanjiku",
      number: "XXXX XXXX XXXX 4444",
      expiry: "03/25",
      cvv: "444",
    },
  },
];

export const bookedAppointments = [];
